rxn_eqn:
  r1: "H2_g + * -> I000*"
  r2: "hexane_g + * -> I001*"
  r3: "1hexene_g + * -> I002*"
  r4: "cis2hexene_g + * -> I003*"
  r5: "trans2hexene_g + * -> I004*"
  r6: "1propene_g + * -> I006*"
  r7: "propane_g + * -> I008*"
  r8: "I000* + * -> I010* + *"
  r9: "I001* + * -> I011* + *"
  r10: "I001* + I010* -> I011* + I000*"
  r11: "I001* + * -> I012* + *"
  r12: "I001* + I010* -> I012* + I000*"
  r13: "I011* + * -> I002* + I010*"
  r14: "I012* + * -> I002* + I010*"
  r15: "I012* + * -> I003* + I010*"
  r16: "I012* + * -> I004* + I010*"
  r17: "I012* + * -> I014* + I006*"
  r18: "I014* + * -> I008* + *"
  r19: "I015* + * -> I008* + *"
  r20: "I006* + I010* -> I014* + *"
  r21: "I006* + I010* -> I015* + *"

int_ads_site:
  I000: 1
  I001: 1
  I002: 1
  I003: 1
  I004: 1
  I006: 1
  I008: 1
  I010: 1
  I011: 1
  I012: 1
  I014: 1
  I015: 1

adsorption:
  collision_theory:
  # k = s0/n0/sqrt(2pi*ma*kb*t) 
    r1: 
      s0: 1
      n0: 1.91e+20 # unit 1/m^2
      ma: 2.01588 # unit g/mol
    r2: 
      s0: 1
      n0: 1.91e+20
      ma: 86.18
    r3: 
      s0: 1
      n0: 1.91e+20
      ma: 84.1608
    r4: 
      s0: 1
      n0: 1.91e+20
      ma: 84.1608
    r5: 
      s0: 1
      n0: 1.91e+20
      ma: 84.1608 
    r6: 
      s0: 1
      n0: 1.91e+20
      ma: 42.081
    r7: 
      s0: 1
      n0: 1.91e+20
      ma: 44.097

reaction_conditions:
  T: [573.15] # unit K
  P_react: 
  - H2_g: 1 # unit bar
    hexane_g: 

reactor:
  None # (TBD; CSTR, PCR)
  
